<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <?php

        if (!empty($data['view']) && file_exists('App/View/' . $data['view'])) {
            require('App/View/' . $data['view']);
        }

    ?>
</body>
</html>