services:
  web:
    container_name: docs-php
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - docs-network
    links:
      - db

  db:
    image: mysql:5.7
    container_name: docs-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - docs-network
    volumes:
      - docs-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678

volumes:
  docs-volume:

networks:
  docs-network:
    driver: bridge