<?php
use App\Controller\View;
?>

<div class="shrink w-[284px]">
    <div id="menul" class="block h-screen max-h-screen overflow-y-auto border-r border-zinc-300">
        <div class="row">
            <div class="logo flex items-center my-4 mx-6">
                <div class="inline-block bg-zinc-200 p-2 rounded">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="36" height="36"><path fill="none" d="M0 0h24v24H0z"/><path d="M7 7V3a1 1 0 0 1 1-1h13a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-4v3.993c0 .556-.449 1.007-1.007 1.007H3.007A1.006 1.006 0 0 1 2 20.993l.003-12.986C2.003 7.451 2.452 7 3.01 7H7zm2 0h6.993C16.549 7 17 7.449 17 8.007V15h3V4H9v3zM4.003 9L4 20h11V9H4.003z"/></svg>
                </div>
                <span class="ml-3 font-bold">Docs</span>
            </div>
            <hr class="border-zinc-300 mb-4">
            <ul>
                <?php View::getFile('_includes/menu_item', ['text' => 'Dashboard', 'link' => '/dashboard']); ?>
                <?php View::getFile('_includes/menu_item', ['text' => 'Páginas', 'link' => '#']); ?>
                <?php View::getFile('_includes/menu_item', ['text' => 'Usuários', 'link' => '/users']); ?>
                <?php View::getFile('_includes/menu_item', ['text' => 'Configurações', 'link' => '#']); ?>
                <?php View::getFile('_includes/menu_item', ['text' => 'Minha Conta', 'link' => '#']); ?>
            </ul>
        </div>
    </div>
</div>